spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.7 # 답변의 창의성 정도
          max-tokens: 512 # 길이 제한

  vectorstore:
    type: memory # RAG - 인메모리 벡터 스토어 사용 (벡터 검색시 사용할 저장소 종류 지정 - 메모리에 저장)

